# compose version 2
version: '2'

volumes:
    database_data:
        driver: local

services:
# Nginx container
    nginx:
        image: nginx:latest
        ports:
            - 80:80 # outised port : inside port
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        volumes_from:
            - php

# PHP container
    php:
        build: ./php/
        expose:
            - 9000
        ports:
            - 25:25
        volumes:
            - ./project/:/var/www/html
            - ./php/php.ini:/usr/local/etc/php/conf.d/php.ini
            - ./php/logs/:/usr/local/etc/php/logs/