# compose version 2
version: '2'

services:
# web server container
    app:
        image: nginx:latest
        ports:
            - 80:80
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        volumes_from:
            - php
        restart: always
        

# PHP container
    php:
        build: ./php/
        expose:
            - 9000
        ports:
            - 25:25
        volumes:
            - ./www/:/var/www/html
            - ./php/php.ini:/usr/local/etc/php/conf.d/php.ini
            - ./php/logs/:/usr/local/etc/php/logs/

